apiVersion: v1
kind: Secret
metadata:
  name: doc-minio-secret
  labels:
    deployment: local
data:
  minio-user: YWRtaW4=
  minio-password: QWRtaW5AMTIz
  minio-url: aHR0cDovL2RvYy1taW5pbzo5MDAw
  minio-access-key: VnlrZnBOMk9UVDZIWXA5YmVmdnQ=
  minio-secret-key: SGhCSFpZcDF4MHdCM2l6aERZemtiWG1RWWhqZmRJd3hiaTVUZ3VwaA==
  minio-bucket-name: cHJqLWRvYw==
