# Define a PVC, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-minio-pvc # name of PVC essential for identifying the storage data
  labels:
    app: doc-minio
    tier: service
spec:
  accessModes:
    - ReadWriteOnce # This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 5Gi # This will tell kubernetes about the amount of space we are trying to claim.
