apiVersion : v1
kind : ConfigMap
metadata:
  name : doc-keycloak-config
  labels:
    deployment: local
data:
  keycloak-url: "http://doc-keycloak:8180/realms/doc-realm/protocol/openid-connect"
  keycloak-scope: "openid"
  keycloak-client-id: "doc-client"
  oauth2-resourceserver-jwt-issuer-uri: "http://doc-keycloak:8180/realms/doc-realm"
  keycloak-http-port: "8180"
  keycloak-db-host: "dpg-cim1untph6eg6k81pehg-a.singapore-postgres.render.com"
  keycloak-db-port: "5432"
  keycloak-database-name: "prj_doc_keycloak_8hva"
