apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-keycloak
  labels:
    app: doc-keycloak
    tier: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-keycloak
  template:
    metadata:
      labels:
        app: doc-keycloak
        tier: service
    spec:
      containers:
        - name: doc-keycloak-service
          image: hcmusdoc/doc-keycloak:latest
          imagePullPolicy: Always
#          livenessProbe:
#            httpGet:
#              port: 8180
#              path: /health/live
#            initialDelaySeconds: 120
#            periodSeconds: 60
          args: [ "start-dev", "--import-realm", "--cache-stack=kubernetes" ]
          ports:
            - containerPort: 8180
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-admin-user

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-admin-password

            - name: KC_FILE
              value: /opt/keycloak/data/import/deployment-realm.json

            - name: KC_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: doc-keycloak-config
                  key: keycloak-http-port

            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: doc-keycloak-config
                  key: keycloak-db-host

            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  name: doc-keycloak-config
                  key: keycloak-db-port

            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: doc-keycloak-config
                  key: keycloak-database-name

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-db-username

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-db-password

            - name: KC_DB_VENDOR
              value: POSTGRES

            - name: KC_DB
              value: postgres

            - name: KC_HEALTH_ENABLED
              value: "true"

            - name: KC_METRICS_ENABLED
              value: "true"

            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: doc-const-config
                  key: vietnam-timezone

---

apiVersion: v1
kind: Service
metadata:
  name: doc-keycloak
  labels:
    app: doc-keycloak
    tier: service
spec:
  selector:
    app: doc-keycloak
    tier: service
  ports:
    - port: 8180
      targetPort: 8180
