apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-keycloak-pv-claim
  labels:
    app: doc-keycloak-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-keycloak-data-pv-claim
  labels:
    app: doc-keycloak-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-keycloak-db
  labels:
    app: doc-keycloak-db
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-keycloak-db
      tier: database
  template:
    metadata:
      labels:
        app: doc-keycloak-db
        tier: database
    spec:
      containers:
        - name: doc-keycloak-db
          image: postgres:15.1-alpine3.17
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-db-username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doc-keycloak-secret
                  key: keycloak-db-password

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: doc-keycloak-config
                  key: keycloak-database-name

            - name: PGDATA
              value: /data/postgres

          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql

            - name: doc-main-data
              mountPath: /data/postgres

      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: doc-keycloak-pv-claim
        - name: doc-main-data
          persistentVolumeClaim:
            claimName: doc-keycloak-data-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: doc-keycloak-db # DNS
  labels:
    app: doc-keycloak-db
    tier: database
spec:
  selector:
    app: doc-keycloak-db
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
