version: '3.7'
services:
  # Databases
  doc-database:
    container_name: doc-main-service-database
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - doc-data:/data/postgres
      - ../../db/src/main:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doc
      PGDATA: /data/postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M

  rabbitmq:
    hostname: localhost
    container_name: rabbitmq-container
    image: rabbitmq:3.9.26-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  doc-data:
  rabbitmq: