version: '3.7'
services:
  # Keycloak
  doc-keycloak:
    container_name: doc-keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak/providers/doc-user-provider-1.0.4.jar:/opt/keycloak/providers/doc-user-provider-1.0.4.jar
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FILE: /opt/keycloak/data/import/realm-export.json
      KC_HTTP_PORT: 8180
      KC_DB_URL_HOST: 13.215.56.216
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: doc-keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_VENDOR: POSTGRES
      KC_DB: postgres
    command:
      - start-dev
      - --import-realm
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  # uncomment this line when using linux
#    extra_hosts:
#      - "host.docker.internal:host-gateway"


volumes:
  doc-keycloak-data:
    name: doc-keycloak-data
    driver: local
