version: '3.7'
services:
  # Databases
  doc-database:
    container_name: doc-database
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doc
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - doc-data:/data/postgres
      - ../../db/src/main:/docker-entrypoint-initdb.d
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Keycloak service
  keycloak-database:
    container_name: keycloak-database
    image: bitnami/postgresql:11.18.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - keycloak-data:/bitnami/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:20.0.3
    volumes:
      - ./keycloak/realms:/opt/bitnami/keycloak/data/import
    depends_on:
      - keycloak-database
    ports:
      - "8180:8180"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.import=/opt/bitnami/keycloak/data/import/realm-export.json
      - KEYCLOAK_HTTP_PORT=8180
      - KEYCLOAK_DATABASE_HOST=keycloak-database
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  doc-data:
  keycloak-data:
    driver: local