version: '3.7'
services:
  # Databases
  doc-database:
    container_name: doc-main-service-database
    image: postgres:15.1-alpine3.17
    ports:
      - "5431:5432"
    volumes:
      - doc-data:/data/postgres
      - ../../db/src/main:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doc
      PGDATA: /data/postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M

volumes:
  doc-data: