version: '3.7'
services:
  postgres:
    container_name: db-container
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doc
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ../../db/src/main:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres: