version: '3.7'
services:
  # Databases
  doc-main-postgres:
    profiles:
      - test-deployment
    container_name: doc-main-postgres
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - doc-main-data:/data/postgres
      - doc-keycloak-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doc
      PGDATA: /data/postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M

  # Keycloak
  doc-keycloak:
    container_name: doc-keycloak
    image: hcmusdoc/doc-keycloak
    ports:
      - "8180:8180"
    volumes:
      - ./keycloak/providers/doc-user-provider-1.0.4.jar:/opt/keycloak/providers/doc-user-provider-1.0.4.jar
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FILE: /opt/keycloak/data/import/realm-export.json
      KC_HTTP_PORT: 8180
      KC_DB_URL_HOST: 13.215.56.216
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: doc-keycloak-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_VENDOR: POSTGRES
      KC_DB: postgres
    command:
      - start-dev
      - --import-realm
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # uncomment below option when using Linux and
  # add this line: 127.0.0.1       host.docker.internal to the /etc/hosts file
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"

  doc-main-service:
    profiles:
      - local-deployment
    container_name: doc-main-service
    image: hcmusdoc/doc-main-service:latest
    pull_policy: never
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - doc-keycloak
    environment:
      DOC_MAIN_SERVICE_SPRING_PROFILES_ACTIVE: local-deployment
      DOC_MAIN_SERVICE_SERVER_PORT: 8080
      DOC_MAIN_SERVICE_DATASOURCE_URL: jdbc:postgresql://13.215.56.216:5432/doc?stringtype=unspecified
      DOC_MAIN_SERVICE_DATASOURCE_USERNAME: admin
      DOC_MAIN_SERVICE_DATASOURCE_PASSWORD: admin
      DOC_MAIN_SERVICE_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://host.docker.internal:8180/realms/doc-realm
      DOC_MAIN_SERVICE_RABBITMQ_HOST: 13.215.56.216
      DOC_MAIN_SERVICE_RABBITMQ_PORT: 5672
      DOC_MAIN_SERVICE_RABBITMQ_USERNAME: guest
      DOC_MAIN_SERVICE_RABBITMQ_PASSWORD: guest
      DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_EXCHANGE: doc.exchange
      DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_ROUTING_KEY: doc.routingkey
      DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_ATTACHMENT_ROUTING_KEY: doc.attachment-routing-key
      DOC_MAIN_SERVICE_HTTP_AUTH_TOKEN: secret
      DOC_MAIN_SERVICE_KEYCLOAK_URL: http://host.docker.internal:8180/realms/doc-realm/protocol/openid-connect
      DOC_MAIN_SERVICE_KEYCLOAK_SCOPE: openid
      DOC_MAIN_SERVICE_KEYCLOAK_CLIENT_ID: doc-client
      DOC_MAIN_SERVICE_KEYCLOAK_CLIENT_SECRET: AW4aUnOGcPpitHX0TI6grfZeA3WLt5ru
      DOC_DB_HOST: 13.215.56.216
      DOC_DATABASE: doc

volumes:
  doc-main-data:
    name: doc-main-data
  doc-keycloak-data:
    name: doc-keycloak-data
    driver: local
