spring:
  profiles:
    active: dev

doc:
  schedule:
    # At 12:00 AM, on day 1 of the month, only in January
    reset-folder-next-number-cron: 0 0 0 1 JAN ?
    # At 12:00:05 AM every day
    update-document-reminder-status-cron: 5 0 0 * * *

firebase:
  googleCredentials: firebase-service-account.json

sendinblue:
  api-key: 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
  sender-name: HCMUS DOC
  sender-email: doc.hcmus@gmail.com