server:
  port: ${DOC_MAIN_SERVICE_SERVER_PORT}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DOC_MAIN_SERVICE_DATASOURCE_URL}
    username: ${DOC_MAIN_SERVICE_DATASOURCE_USERNAME}
    password: ${DOC_MAIN_SERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DOC_MAIN_SERVICE_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

  rabbitmq:
    host: ${DOC_MAIN_SERVICE_RABBITMQ_HOST}
    port: ${DOC_MAIN_SERVICE_RABBITMQ_PORT}
    username: ${DOC_MAIN_SERVICE_RABBITMQ_USERNAME}
    password: ${DOC_MAIN_SERVICE_RABBITMQ_PASSWORD}
    template:
      exchange: ${DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_EXCHANGE}
      routing-key: ${DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_ROUTING_KEY}
      attachment-routing-key: ${DOC_MAIN_SERVICE_RABBITMQ_TEMPLATE_ATTACHMENT_ROUTING_KEY}

logging:
  level:
    sql: debug

doc:
  http:
    auth-token-header-name: DOC-Auth-Token
    auth-token: ${DOC_MAIN_SERVICE_HTTP_AUTH_TOKEN}

keycloak:
  url: ${DOC_MAIN_SERVICE_KEYCLOAK_URL}
  scope: ${DOC_MAIN_SERVICE_KEYCLOAK_SCOPE}
  client-id: ${DOC_MAIN_SERVICE_KEYCLOAK_CLIENT_ID}
  client-secret: ${DOC_MAIN_SERVICE_KEYCLOAK_CLIENT_SECRET}
