spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5431/doc?stringtype=unspecified
    username: admin
    password: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/doc-realm

logging:
  level:
    sql: debug

doc:
  http:
    auth-token-header-name: DOC-Auth-Token
    auth-token: secret

keycloak:
  url: http://host.docker.internal:8180/realms/doc-realm/protocol/openid-connect/token
  scope: openid
  client-id: doc-client
  client-secret: AW4aUnOGcPpitHX0TI6grfZeA3WLt5ru
