spring:
  profiles:
    active: dev

doc:
  schedule:
    # At 12:00 AM, on day 1 of the month, only in January
    reset-folder-next-number-cron: 0 0 0 1 JAN ?
    # At 12:00:05 AM every day
    update-document-reminder-status-cron: 5 0 0 * * *
