--liquibase formatted sql
--changeset author:031

SET SEARCH_PATH TO doc_main;

ALTER TABLE INCOMING_DOCUMENT ALTER COLUMN SUMMARY DROP NOT NULL;
ALTER TABLE OUTGOING_DOCUMENT ALTER COLUMN SUMMARY DROP NOT NULL;
